### ISSUE TITLE
Handle job which get rejected by godocker scheduler 

### ISSUE THREAD

**Issue by varunshankar** [varunshankar/galaxy-godocker#10]
Job which are getting rejected by godocker, needs to be deleted in godocker and the jobs must be failed in galaxy.

**Comment by varunshankar** [comment]
![rejected_by_scheduler](https://cloud.githubusercontent.com/assets/5507980/16356435/e35e007e-3af4-11e6-87e9-de39587e24e6.png)

**Comment by osallou** [comment]
job can be rejected by scheduler because there is no available cpu/ram etc.. so job remains in pending state = queued.
Job should not be killed if this occurs, and galaxy job state should remain queued. job will be scheduled when resources are available

**Comment by varunshankar** [comment]
So... if rejected by scheduler , will it automatically execute the job when resources are available. 

Can we get the status of rejected by scheduler and handle it specially in galaxy. Like.. instead of job queued as status in galaxy, we can tell that the job is waiting for resources.

I think this happened due to the mentioning of db in volume

**Comment by osallou** [comment]
Job will be rescheduled automatically when possible. Simply keep job as
queued in galaxy.

Le sam. 25 juin 2016 14:52, Varun Shankar S <notifications@github.com> a
écrit :
