### ISSUE TITLE
add god.log and god.err to galaxy job outputs

### ISSUE THREAD

**Issue by osallou** [varunshankar/galaxy-godocker#4]
associate god.log and god.err files to galaxy jobs to get stdout and stderr

**Comment by varunshankar** [comment]
Completed:
god.log -> job_state.output_file
god.err -> job_state.error_file
task['status']['exitcode'] -> job_state.exit_code_file

Todo:
? -> .sh file

**Comment by osallou** [comment]
We have no .sh, we use runner command line. So i don t know if we need to
write it. Seem not written in some other runners.
Anyway it is not mandatory

Le mar. 14 juin 2016 23:39, Varun Shankar S <notifications@github.com> a
écrit :

**Comment by varunshankar** [comment]
yes, It seems to be unnecessary , so I am not making extra reads/writes.
