### ISSUE TITLE
use project from config

### ISSUE THREAD

**Issue by osallou** [varunshankar/galaxy-godocker#5]
project in task creation should be loaded from runner config just like godocker_master.

If not present (optional), then project should not be specified in task.

**Comment by varunshankar** [comment]
project = str(self.runner_params["galaxy_master"])  
causes post_task to fail with 403 : Forbidden access error from godocker

**Comment by osallou** [comment]
Why do you name param galaxy_master?
It should be godocker_project.

You should print content of project, there is certainly an issue reading
param.

If param is not set, then project should not be set in job structure.

Le jeu. 16 juin 2016 22:53, Varun Shankar S <notifications@github.com> a
écrit :

**Comment by osallou** [comment]
You have set project name in config GoDockerIntegration.
This is not a valid project, only "galaxy" project exists in our godocker setup (and setup to mount galaxy dirs)

**Comment by varunshankar** [comment]
If param is not set means that the parameter is not set in job_conf.xml ?

**Comment by osallou** [comment]
If not set in job_conf.xml, then it must not be set in job json you send to
godocker.

Le sam. 18 juin 2016 22:05, Varun Shankar S <notifications@github.com> a
écrit :

**Comment by varunshankar** [comment]
Hi,
I have done the required changes for project.

**Comment by osallou** [comment]
no, you simply set project to empty in this case. this is not correct.

    ==>      project = None
               try:
                    log.debug(self.runner_params["godocker_project"])
                    project = str(self.runner_params["godocker_project"])
                except KeyError:
    ==>           log.warn('godocker_project not defined, using defaults")


then in job = {....  } , simply remove user from job definition.

Then put project name if defined.

    if project is not None:
        job['user'] = {"project": project}

**Comment by varunshankar** [comment]
okay... i have done the changes... I tested with specifying project and without specifying project. It is working properly.

**Comment by osallou** [comment]
looks ok in code to close issue, do not forget to update code in VM
