### ISSUE TITLE
test failure to get god.log and god.err

### ISSUE THREAD

**Issue by osallou** [varunshankar/galaxy-godocker#7]
if files are not present, job should end in failure.

**Comment by varunshankar** [comment]
Okay, I have updated the code.

**Comment by varunshankar** [comment]
Can I close this issue ?

**Comment by osallou** [comment]
Yes but on except you should put error log instead of debug:

except IOError:
                log.debug("IO Error occurred when accessing the files!!")
==> except IOError as e:
==>           log.error('Could not access task log file %s' % str(e))

**Comment by varunshankar** [comment]
Yes.. done

**Comment by osallou** [comment]
you can close it
