### ISSUE TITLE
Add possibility to specify some godocker volumes in destination params

### ISSUE THREAD

**Issue by osallou** [varunshankar/galaxy-godocker#9]
In destination, add possibility to specify a param godocker_volumes
godocker_volumes would be a list of volume names (comma separated) to be mounted in container (according to godocker allowed volumes).

For each requested volume name, the job task would set the job['container']['volumes'] element.

Example:

destination param godocker_volumes => "home,db", supposing that home and db are allowed volumes in godocker config.

job['container']['volumes'] = [ {'name': 'home'}, {'name': 'db'}]

**Comment by varunshankar** [comment]
After adding support for volumes, every job is getting rejected in godocker. Is the job structure not formed properly !

**Comment by osallou** [comment]
What rejection do you have ? please provide the job structure you send so that I can check it.
Also, do you ask "existing" volumes ?

**Comment by osallou** [comment]
I see in your job_conf:
<param id="godocker_volumes">home,db</param>

but "db" is not a valid volume in your godocker install (see volumes in "new job" web interface).
I gave above an example, this must of course be adapted

**Comment by varunshankar** [comment]
I have added godocker_volumes and virtualenv in job_conf. Exception handling is also done. Waiting for your approval to close this issue

**Comment by osallou** [comment]
looks ok

**Comment by osallou** [comment]
indeed wheezy libc version is a little too old compared to the python version used on VM.
